[tool.poetry]
name = "blockchain-chat"
version = "0.1.0"
description = ""
authors = ["TOFU-0218 <maikura5963@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
